# Generated by Django 5.2.8 on 2026-02-24 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('icon', models.CharField(help_text="Lucide React icon name (e.g., 'CookingPot')", max_length=50)),
                ('description', models.TextField(blank=True)),
                ('price_min', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('price_max', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order on frontend')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_phone', models.CharField(help_text='Customer WhatsApp number with country code', max_length=20)),
                ('customer_name', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField(blank=True, help_text='Initial message sent to customer')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('message_sent', 'WhatsApp Message Sent'), ('in_conversation', 'In Conversation'), ('assigned', 'Expert Assigned'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('conversation_step', models.PositiveIntegerField(default=0, help_text='Current step in conversation tree')),
                ('notes', models.TextField(blank=True, help_text='Internal notes or customer responses')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='services.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
