# Generated by Django 5.2.8 on 2026-02-24 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='assigned_expert',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Logged-in user who made the request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='work_done',
            field=models.BooleanField(default=False, help_text='Has the work been completed?'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='work_notes',
            field=models.TextField(blank=True, help_text='Details about work done / pending'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(help_text='Lucide React icon name', max_length=50),
        ),
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='conversation_step',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='customer_phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('message_sent', 'WhatsApp Message Sent'), ('in_conversation', 'In Conversation'), ('assigned', 'Expert Assigned'), ('in_progress', 'Work In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
